### PR TITLE
Propose KUBECONFIG

### PR DESCRIPTION
**Pull request by marcelldls**

### CODE REVIEW

**Review by gilesknap — CHANGES_REQUESTED** [review]
Ah. That makes more sense. I guess K3S just has a different default for KUBECONFIG.

Please can you make this work for bash users too.

**Comment by marcelldls** [comment]
Sorry I think the env var should have been exported. This was more to start a conversation about not reinstalling kubectl. I think the cleanest I have is
```
echo 'export KUBECONFIG=$HOME/.kube/config' >> $HOME/.profile
source $HOME/.profile
```
But if you open a new terminal you have to source again. Or log out and in I guess?

**Comment by gilesknap** [comment]
Yeah that is the annoying thing about using .profile.

I'm OK with what you suggest above, plus 'log out for this to be set for all shells'. Or similar.

**Comment by marcelldls** [comment]
@gilesknap Done

**Pull request merged**
